# Generated by Django 3.2.12 on 2022-03-31 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_alter_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
