# Generated by Django 3.2.12 on 2022-04-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0003_alter_time_work_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_work',
            name='time_start',
            field=models.DateTimeField(null=True),
        ),
    ]
