# Generated by Django 3.2.12 on 2022-04-01 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0003_task_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_finish', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date_finished',
        ),
        migrations.RemoveField(
            model_name='task',
            name='time',
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_finish', models.DateTimeField()),
                ('time_for_execution', models.CharField(max_length=150)),
                ('time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managers.task')),
            ],
        ),
    ]
