# Generated by Django 3.2.12 on 2022-04-06 12:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managers', '0004_alter_time_work_time_start'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Time_Work',
            new_name='TimeWork',
        ),
    ]
