# Generated by Django 3.2.12 on 2022-04-01 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0004_auto_20220401_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='time',
        ),
        migrations.DeleteModel(
            name='Time_work',
        ),
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
