# Generated by Django 3.2.12 on 2022-04-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0005_rename_time_work_timework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timework',
            name='time',
        ),
        migrations.AddField(
            model_name='timework',
            name='minutes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
