# Generated by Django 3.2.12 on 2022-04-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0006_auto_20220401_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(auto_now_add=True)),
                ('time_finish', models.DateTimeField()),
            ],
        ),
    ]
