# Generated by Django 3.2.12 on 2022-04-07 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0007_alter_time_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='task',
            field=models.OneToOneField(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time', to='managers.task'),
        ),
    ]
