# Generated by Django 3.2.12 on 2022-04-01 09:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0008_auto_20220401_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_work',
            name='time',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
