# Generated by Django 3.2.12 on 2022-04-12 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0009_alter_time_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timework',
            name='time_finish',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timework',
            name='time_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
