# Generated by Django 3.2.12 on 2022-04-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0010_alter_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
