# Generated by Django 3.2.12 on 2022-04-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0010_auto_20220412_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timework',
            name='time_finish',
            field=models.DateTimeField(null=True),
        ),
    ]
