# Generated by Django 3.2.12 on 2022-04-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0011_alter_timework_time_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timework',
            name='time_start',
            field=models.DateTimeField(null=True),
        ),
    ]
