# Generated by Django 3.2.12 on 2022-04-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0012_auto_20220404_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='minutes',
            field=models.IntegerField(null=True),
        ),
    ]
