# Generated by Django 3.2.12 on 2022-04-04 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0014_remove_time_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='time',
            new_name='task',
        ),
    ]
