# Generated by Django 3.2.12 on 2022-04-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0015_rename_time_time_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='minutes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
